export LANG=en_US.UTF-8
export LC_CTYPE=en_US.UTF-8

GIT_PS1_SHOWDIRTYSTATE=true
export LS_OPTIONS='--color=auto'
export CLICOLOR='Yes'
export LSCOLORS=gxfxbEaEBxxEhEhBaDaCaD
BREW_PREFIX=$(brew --prefix)

if [ -f $BREW_PREFIX/etc/bash_completion ]; then
  . $BREW_PREFIX/etc/bash_completion
  if [ -f $BREW_PREFIX/etc/bash_completion.d/git-prompt.sh ]; then
    . $BREW_PREFIX/etc/bash_completion.d/git-prompt.sh	
    export PS1="\u@\h \e[30;1m\w\e[0m\$(__git_ps1) [\$?]\n\$ "
  fi
fi

# Set current directory name as terminal title
# Source https://gist.github.com/phette23/5270658
export PROMPT_COMMAND='echo -ne "\033]0;${PWD##*/}\007"'

# SBT
if which sbtenv > /dev/null; 
then 
	eval "$(sbtenv init - --no-rehash)"; 
  (sbtenv rehash &) 2> /dev/null
fi

# Ruby
if which rbenv > /dev/null; 
then 
  eval "$(rbenv init - --no-rehash)";
  (rbenv rehash &) 2> /dev/null	
fi

# Java
if which jenv > /dev/null
then
  eval "$(jenv init - --no-rehash)"
  (jenv rehash &) 2> /dev/null	
fi

# Python
if which pyenv > /dev/null 
then 
  eval "$(pyenv init - --no-rehash)"
  (pyenv rehash &) 2> /dev/null
  eval "$(pyenv virtualenv-init -)"	
fi

if [ -f "$BREW_PREFIX/share/cracklib-words" ]; then
  export CRACKLIB_DICTPATH="$BREW_PREFIX/share/cracklib-words"
fi

# Suspend Ctrl+S combination
stty -ixon 2> /dev/null

# Add ~/bin to PATH
if [ -d "$HOME/bin" ]; then
  export PATH="$HOME/bin:$PATH"
fi

# And /usr/local/sbin
export PATH="$PATH:/usr/local/sbin"

# Set Sublime as default editor
if which subl > /dev/null; then export EDITOR="subl -w"; fi

# Aliases
alias prof="$EDITOR ~/.bash_profile"
alias reprof=". ~/.bash_profile"
# This is to suppress brew complaints related to pyenv
alias brew="env PATH=${PATH//$(pyenv root)\/shims:/} brew"

# Additional and private variables
USER_PROFILE_DIR="$HOME/.profile.d"

# source profile directory 
if [[ -d $USER_PROFILE_DIR && -r $USER_PROFILE_DIR && \
	-x $USER_PROFILE_DIR ]]; then
	for i in $(LC_ALL=C command ls "$USER_PROFILE_DIR"); do
		i=$USER_PROFILE_DIR/$i
		[[ ${i##*/} != @(*~|*.bak|*.swp|\#*\#|*.dpkg*|*.rpm@(orig|new|save)|Makefile*) \
			&& -f $i && -r $i ]] && . "$i"
	done
fi

